# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true




#  CodeRabbit Commands (Invoked using PR comments)
# @coderabbitai pause to pause the reviews on a PR.
# @coderabbitai resume to resume the paused reviews.
# @coderabbitai review to trigger an incremental review. This is useful when automatic reviews are disabled for the repository.
# @coderabbitai full review to do a full review from scratch and review all the files again.
# @coderabbitai summary to regenerate the summary of the PR.
# @coderabbitai generate docstrings to generate docstrings for this PR.
# @coderabbitai resolve resolve all the CodeRabbit review comments.
# @coderabbitai configuration to show the current CodeRabbit configuration for the repository.
# @coderabbitai help to get help.